import pygame
from pygame.locals import *
pygame.init()
screen = pygame.display.set_mode((1080 , 720))
#tutorial
tut1 = pygame.image.load('D:/Fucked up in da crib/game/tutorial/Tutorial.png').convert_alpha()
tut2 = pygame.image.load('D:/Fucked up in da crib/game/tutorial/Tutorial2.png').convert_alpha()
tut3 = pygame.image.load('D:/Fucked up in da crib/game/tutorial/Tutorial3.png').convert_alpha()
tut4 = pygame.image.load('D:/Fucked up in da crib/game/tutorial/Tutorial4.png').convert_alpha()
tut5 = pygame.image.load('D:/Fucked up in da crib/game/tutorial/Tutorial5.png').convert_alpha()
tut6 = pygame.image.load('D:/Fucked up in da crib/game/tutorial/Tutorial6.png').convert_alpha()

tut1 = pygame.transform.scale(tut1,(1080,720))
tut2 = pygame.transform.scale(tut2,(1080,720))
tut3 = pygame.transform.scale(tut3,(1080,720))
tut4 = pygame.transform.scale(tut4,(1080,720))
tut5 = pygame.transform.scale(tut5,(1080,720))
tut6 = pygame.transform.scale(tut6,(1080,720))
#goofy slike
slika1 = pygame.image.load('D:/Fucked up in da crib/game/goofy/1.png').convert_alpha()
slika2 = pygame.image.load('D:/Fucked up in da crib/game/goofy/2.jpg').convert_alpha()
slika3 = pygame.image.load('D:/Fucked up in da crib/game/goofy/3.jpg').convert_alpha()
slika4 = pygame.image.load('D:/Fucked up in da crib/game/goofy/4.jpg').convert_alpha()
slika5 = pygame.image.load('D:/Fucked up in da crib/game/goofy/5.jpg').convert_alpha()
slika6 = pygame.image.load('D:/Fucked up in da crib/game/goofy/6.jpg').convert_alpha()
slika7 = pygame.image.load('D:/Fucked up in da crib/game/goofy/7.jpg').convert_alpha()
slika8 = pygame.image.load('D:/Fucked up in da crib/game/goofy/8.jpg').convert_alpha()
slika9 = pygame.image.load('D:/Fucked up in da crib/game/goofy/9.png').convert_alpha()
slika10 = pygame.image.load('D:/Fucked up in da crib/game/goofy/10.png').convert_alpha()
slika11 = pygame.image.load('D:/Fucked up in da crib/game/goofy/11.jpg').convert_alpha()
slika12 = pygame.image.load('D:/Fucked up in da crib/game/goofy/12.jpg').convert_alpha()
slika13 = pygame.image.load('D:/Fucked up in da crib/game/yea.jpg').convert_alpha()

slika1 = pygame.transform.scale(slika1,(400,200))
slika2 = pygame.transform.scale(slika2,(400,200))
slika3 = pygame.transform.scale(slika3,(400,200))
slika4 = pygame.transform.scale(slika4,(400,200))
slika5 = pygame.transform.scale(slika5,(400,200))
slika6 = pygame.transform.scale(slika6,(400,200))
slika7 = pygame.transform.scale(slika7,(400,200))
slika8 = pygame.transform.scale(slika8,(400,200))
slika9 = pygame.transform.scale(slika9,(400,200))
slika10 = pygame.transform.scale(slika10,(400,200))
slika11 = pygame.transform.scale(slika11,(400,200))
slika12 = pygame.transform.scale(slika12,(400,200))
slika13 = pygame.transform.scale(slika13,(1080,720))
#buttoni
play = pygame.image.load('D:/Fucked up in da crib/game/play.png').convert_alpha()
options = pygame.image.load('D:/Fucked up in da crib/game/options.png').convert_alpha()
resume = pygame.image.load('D:/Fucked up in da crib/game/resume.png').convert_alpha()
quit1 = pygame.image.load('D:/Fucked up in da crib/game/quit.png').convert_alpha()
goofy = pygame.image.load('D:/Fucked up in da crib/game/goofy_pictures.png').convert_alpha()
back = pygame.image.load('D:/Fucked up in da crib/game/back.png').convert_alpha()
tutorial = pygame.image.load('D:/Fucked up in da crib/game/tutorial.png').convert_alpha()
next1 = pygame.image.load('D:/Fucked up in da crib/game/next.png').convert_alpha()
exit1 = pygame.image.load('D:/Fucked up in da crib/game/exit.png').convert_alpha()
dont = pygame.image.load('D:/Fucked up in da crib/game/dont.png').convert_alpha()
menu = pygame.image.load('D:/Fucked up in da crib/game/menu.png').convert_alpha()

#pitanja buttoni
pitanje1_1 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje1_1.png').convert_alpha()
pitanje1_2 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje1_2.png').convert_alpha()
pitanje1_3 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje1_3.png').convert_alpha()
pitanje1_4 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje1_4.png').convert_alpha()

pitanje2_1 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje2_1.png').convert_alpha()
pitanje2_2 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje2_2.png').convert_alpha()
pitanje2_3 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje2_3.png').convert_alpha()
pitanje2_4 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje2_4.png').convert_alpha()

pitanje3_1 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje3_1.png').convert_alpha()
pitanje3_2 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje3_2.png').convert_alpha()
pitanje3_3 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje3_3.png').convert_alpha()
pitanje3_4 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje3_4.png').convert_alpha()

pitanje4_1 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje4_1.png').convert_alpha()
pitanje4_2 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje4_2.png').convert_alpha()
pitanje4_3 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje4_3.png').convert_alpha()
pitanje4_4 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje4_4.png').convert_alpha()

pitanje5_1 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje5_1.png').convert_alpha()
pitanje5_2 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje5_2.png').convert_alpha()
pitanje5_3 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje5_3.png').convert_alpha()
pitanje5_4 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje5_4.png').convert_alpha()

pitanje6_1 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje6_1.png').convert_alpha()
pitanje6_2 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje6_2.png').convert_alpha()
pitanje6_3 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje6_3.png').convert_alpha()
pitanje6_4 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje6_4.png').convert_alpha()

pitanje7_1 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje7_1.png').convert_alpha()
pitanje7_2 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje7_2.png').convert_alpha()
pitanje7_3 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje7_3.png').convert_alpha()
pitanje7_4 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje7_4.png').convert_alpha()

pitanje8_1 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje8_1.png').convert_alpha()
pitanje8_2 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje8_2.png').convert_alpha()
pitanje8_3 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje8_3.png').convert_alpha()
pitanje8_4 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje8_4.png').convert_alpha()

pitanje9_1 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje9_1.png').convert_alpha()
pitanje9_2 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje9_2.png').convert_alpha()
pitanje9_3 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje9_3.png').convert_alpha()
pitanje9_4 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje9_4.png').convert_alpha()

pitanje0_1 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje0_1.png').convert_alpha()
pitanje0_2 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje0_2.png').convert_alpha()
pitanje0_3 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje0_3.png').convert_alpha()
pitanje0_4 = pygame.image.load('D:/Fucked up in da crib/game/pitanja/pitanje0_4.png').convert_alpha()

#win
winscr = pygame.image.load('D:/Fucked up in da crib/game/winscr.png').convert_alpha()
tu = pygame.image.load('D:/Fucked up in da crib/game/tu.png').convert_alpha()
karlo = pygame.image.load('D:/Fucked up in da crib/game/karlo.jpg').convert_alpha()
karlo = pygame.transform.scale(karlo,(400,200))
ja = pygame.image.load('D:/Fucked up in da crib/game/ja.jpg').convert_alpha()
ja = pygame.transform.scale(ja,(150,333))
man = pygame.image.load('D:/Fucked up in da crib/game/man.jpg').convert_alpha()
man = pygame.transform.scale(man,(500,200))
gej = pygame.image.load('D:/Fucked up in da crib/game/gej.jpg').convert_alpha()
gej = pygame.transform.scale(gej,(80,80))
jes = pygame.image.load('D:/Fucked up in da crib/game/jes.jpg').convert_alpha()
jes = pygame.transform.scale(jes,(120,400))
